networks:
  development:

volumes:
  postgres_data:

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - development
